ALTER TABLE clienti
  ADD COLUMN IF NOT EXISTS tipo TEXT NOT NULL DEFAULT 'privato',
  ADD COLUMN IF NOT EXISTS ragione_sociale TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS via TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS civico TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS cap TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS citta TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS provincia TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS nazione TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS codice_sdi TEXT DEFAULT NULL;
-- Keep indirizzo column for backward compatibility with existing data
